USE ENCHERES

ALTER TABLE UTILISATEURS
ADD CONSTRAINT UK_telephone
UNIQUE(telephone)

ALTER TABLE UTILISATEURS
ADD CONSTRAINT UK_pseudo
UNIQUE(pseudo)

ALTER TABLE UTILISATEURS
ADD CONSTRAINT UK_email
UNIQUE(email)

GO